### ISSUE TITLE
Code review.

### ISSUE THREAD

**Issue by kgryte** [compute-io/matrix-function#1]

**Comment by kgryte** [comment]
For an initial concept of how it would be incorporated in compute modules and elsewhere, see [beta](https://github.com/compute-io/beta/blob/623e80e9027fb833aa15b747f09c77e0a28f67e2/lib/matrix-matrix.js).

**Comment by Planeshifter** [comment]
Looks all well to me, but I have a proposal of how one can avoid using `eval`: 
No matter whether the user calls the `create` function with a `fcn` argument or not, I propose to use `( new Function ( f ) )();` to generate the `apply` function. If I see it correctly, the only reason that you are currently using `eval` is that you have to be able to access `fcn`, and thus need to create the function in the local scope. I don't think having access to a local scope is necessary, though: We could simply add a property to the returned function which contains a reference to the function to be applied. Something like this works:

``` javascript
/* jshint evil:true */
'use strict';

// MODULES //

var isPositiveInteger = require( 'validate.io-positive-integer' ),
    isFunction = require( 'validate.io-function' );


// CREATE //

/**
* FUNCTION: create( [fcn,] num )
*   Returns a function for applying a function to each matrix element.
*
* @param {Function} [fcn] - function to apply. If not provided, a function must be provided at runtime.
* @param {Number} num - number of matrix arguments (including the output matrix)
* @returns {Function} apply function
*/
function create() {
    var nargs = arguments.length,
        flg,
        num,
        fcn,
        n,
        f,
        i;

    if ( nargs === 1 ) {
        num = arguments[ 0 ];
        flg = true;
    }
    else if ( isFunction( arguments[ 0 ] ) ) {
        fcn = arguments[ 0 ];
        num = arguments[ 1 ];
        flg = false;
    }
    else {
        throw new TypeError( 'invalid input arguments. Must provide a function to apply and the number of matrix arguments. Values: `' + arguments + '`.' );
    }
    if ( !isPositiveInteger( num ) ) {
        throw new TypeError( 'invalid input arguments. Parameter specifying the number of matrix arguments must be a positive integer. Value: `' + num + '`.' );
    }
    n = num - 1;

    // Code generation. Start with the function definition...
    f = 'return function apply(';

    // Check if a function will be provided at runtime...
    if ( flg ) {
        f += 'fcn,';
    }
    // Create the matrix arguments...
    // => function apply( [fcn,] o, m1, m2,...) {
    f += 'o,';
    for ( i = 1; i < num; i++ ) {
        f += 'm' + i;
        if ( i < n ) {
            f += ',';
        }
    }
    f += '){';

    // Create the function body...

    // Create internal variables...
    // => var M, N, i, j;
    f += 'var M,N,i,j;';
    // Perform shape validation (where we assume all input args are matrices)...
    f += 'M=o.shape[0];';
    f += 'N=o.shape[1];';
    for ( i = 1; i < num; i++ ) {
        f += 'if(m'+i+'.shape[0]!==M||m'+i+'.shape[1]!==N){';
        f += 'throw new Error(\'invalid input argument. All matrices must have the same dimensions.\');';
        f += '}';
    }
    /*
        var M, N,
            i, j;

        M = o.shape[ 0 ];
        N = o.shape[ 1 ];
        if ( m1.shape[0] !== M || m1.shape[1] !== N ) {
            throw new Error(...);
        }
        ...
    */

    // Apply the function to each matrix element...
    f += 'for(i=0;i<M;i++){';
    f += 'for(j=0;j<N;j++){';
    f += 'o.set(i,j,apply.fcn(';
    for ( i = 1; i < num; i++ ) {
        f += 'm' + i + '.get(i,j)';
        if ( i < n ) {
            f += ',';
        }
    }
    f += '));';
    f += '}}';
    /*
        for ( i = 0; i < M; i++ ) {
            for ( j = 0; j < N; j++ ) {
                o.set( i, j, apply.fcn( m1.get(i,j), m2.get(i,j),...) );
            }
        }
    */

    // Return the output matrix...
    f += 'return o;';

    // Close the function:
    f += '};';

    // Create the function
    var ret = ( new Function ( f ) )();
    ret.fcn = fcn;
    return ret;
    /*
        function apply( [fcn,] o, m1, m2,...) {
            var M, N,
                i, j;

            M = o.shape[ 0 ];
            N = o.shape[ 1 ];
            if ( m1.shape[0] !== M ||
                m1.shape[1] !== N
            ) {
                throw new Error(...);
            }
            ...
            for ( i = 0; i < M; i++ ) {
                for ( j = 0; j < N; j++ ) {
                    o.set( i, j, fcn( m1.get(i,j), m2.get(i,j),...) );
                }
            }
            return o;
        }
    */
} // end FUNCTION create()


// EXPORTS //

module.exports = create;
```

What do you think? Or am I missing something?

**Comment by kgryte** [comment]
`eval` **and** `new Function()` can both violate a [CSP](http://www.html5rocks.com/en/tutorials/security/content-security-policy/#eval-too). `new Function()` is effectively `eval` dressed in different clothes. You cannot whitelist one without whitelisting the other. The note in the README is to convey not that only `eval` is used, but that `string` evaluation is used. 

So, unfortunately, while your proposal works, it does not prevent this module being used in a way which violates a CSP.

Or wait...did I misread your proposal? Do you just want to avoid the `local` scope regardless?

**Comment by Planeshifter** [comment]
Yeah, don't think we need accessing the local scope of the `create` function. I thought it was generally preferred to use `new Function()` instead of  `eval` as it ensures that the evaluated code can only access its own and global variables. But obviously both solutions work, and I don't hold any strong opinions about this.

**Comment by kgryte** [comment]
A few thoughts, which skew toward your proposal.
1) We may only want to worry about having access to local variables if those variables are mutable and can be manipulated for nefarious purposes. The only variable which could be affected within the created method is the enclosed `fcn`. The variable could be reassigned within a provided apply `function`, thus allowing injection.

The validation module references could also be reassigned within the parent scope, allowing injection during input argument validation, and thus affect all subsequent calls to `create()`.

2) If we publicly assign the enclosed function to the created method, reassignment is still possible and so is injection within the created method.
3) which is more performant? Will the compiler dereference `apply.fcn` to `fcn` and have the same perf numbers as a closure?

**Comment by kgryte** [comment]
@Planeshifter Thanks for your feedback and reviewing!
